name: Coverage Reporting

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor == 'ahmedfaiyaz-6sense'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: yarn install

    - name: Run Test & Coverage
      run: yarn test:cov

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info